"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Insert Python script file']
DATA_FILES = []
OPTIONS = {'includes':['os','sys','tkinter','pynput','pynput.keyboard._darwin','pynput.mouse._darwin','keyboard','time','threading']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app']
)
